# Housing Price Predictor Configuration

# Data paths
data:
  zillow_path: "data/zillow_data"
  cache_dir: "data/cache"
  synthetic_dir: "data/synthetic"
  
# Model configurations
models:
  linear_regression:
    fit_intercept: true
    normalize: false
    
  random_forest:
    n_estimators: 100
    max_depth: 20
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    
  xgboost:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    
  neural_network:
    hidden_layer_sizes: [100, 50]
    activation: "relu"
    solver: "adam"
    alpha: 0.001
    learning_rate: "constant"
    max_iter: 1000
    random_state: 42

# Training parameters
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  scoring: "r2"
  
# Logging configuration
logging:
  level: "INFO"
  file: "logs/housing_predictor.log"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  rotation: "10 MB"
  retention: "30 days"

# Visualization settings
visualization:
  style: "seaborn-v0_8"
  figure_size: [12, 8]
  dpi: 100
  save_format: "png"
  show_plots: true
  
# Web interface settings
web_app:
  port: 8501
  host: "localhost"
  debug: false
  theme: "light"
  
# Performance settings
performance:
  n_jobs: -1
  memory_limit: "4GB"
  use_gpu: false
  cache_predictions: true
